namespace PointerDemo
{
    [default_interface]
    runtimeclass PointerRenderer : Windows.UI.Xaml.Controls.SwapChainPanel
    {
        PointerRenderer();

        Boolean CaptureInputOnPress{ get; set; };
        static Windows.UI.Xaml.DependencyProperty CaptureInputOnPressProperty{ get; };
    }
}